// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoqrJIOA_HP2ZtSGlOPgLdvTJLTWUgU4',
    appId: '1:389804623700:web:2175570ad9330f1f976ac1',
    messagingSenderId: '389804623700',
    projectId: 'noteplus-app',
    authDomain: 'noteplus-app.firebaseapp.com',
    storageBucket: 'noteplus-app.firebasestorage.app',
    measurementId: 'G-D3DYJZG2E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODVJlRbwuE4s5fa_ebYFg0jm2HqcJppM',
    appId: '1:389804623700:android:fc632effce9e51a9976ac1',
    messagingSenderId: '389804623700',
    projectId: 'noteplus-app',
    storageBucket: 'noteplus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdI_Msi5Ecgr3AqmJIcBNspv55X3cpVKQ',
    appId: '1:389804623700:ios:a34ca64e33c8685a976ac1',
    messagingSenderId: '389804623700',
    projectId: 'noteplus-app',
    storageBucket: 'noteplus-app.firebasestorage.app',
    iosBundleId: 'com.example.noteplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdI_Msi5Ecgr3AqmJIcBNspv55X3cpVKQ',
    appId: '1:389804623700:ios:a34ca64e33c8685a976ac1',
    messagingSenderId: '389804623700',
    projectId: 'noteplus-app',
    storageBucket: 'noteplus-app.firebasestorage.app',
    iosBundleId: 'com.example.noteplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoqrJIOA_HP2ZtSGlOPgLdvTJLTWUgU4',
    appId: '1:389804623700:web:be3b9fac3376bb74976ac1',
    messagingSenderId: '389804623700',
    projectId: 'noteplus-app',
    authDomain: 'noteplus-app.firebaseapp.com',
    storageBucket: 'noteplus-app.firebasestorage.app',
    measurementId: 'G-THXRJ6WT4L',
  );
}
